fix: use before_action instead of before_filter clauses
This comes from the error: undefined method `before_filter' for Spree::CheckoutController:Class (NoMethodError) in both files